package vexelray.dasumgui;

import sibarum.dasum.gui.core.render.Texture;
import sibarum.dasum.gui.core.text.AtlasData;
import sibarum.dasum.gui.core.text.FontGroup;
import sibarum.dasum.gui.core.text.FontGroups;
import sibarum.dasum.gui.core.text.Icon;

/**
 * Loads and registers the vexelray MSDF font atlases generated by the
 * dasum-msdf-maven-plugin (see this module's pom): the broad-coverage
 * {@code primary} text atlas, the {@code mono} (JetBrains Mono) atlas for
 * editor/code surfaces, and the Lucide {@code icons} atlas.
 *
 * <p>Shared by every dasum-based vexelray app (editor, viewer, ...). The atlas
 * PNG/JSON resources live on this module's classpath, so any module that depends
 * on {@code vexelray-dasumgui} can call {@link #loadAndRegister()}.
 *
 * <p>Must be called <em>after</em> {@code Gl.load()} — the textures need a live
 * GL context. Hold the returned handle for the lifetime of the window and
 * {@link #close()} it on shutdown (it owns the GL textures); a
 * try-with-resources around the event loop is the intended shape.
 */
public final class Atlases implements AutoCloseable {

    /** Font-group name for the primary (broad Unicode) text atlas. */
    public static final String PRIMARY = FontGroups.DEFAULT;
    /** Font-group name for the monospace (JetBrains Mono) text atlas. */
    public static final String MONO = "mono";
    /** Font-group name for the Lucide icon atlas. */
    public static final String ICONS = Icon.DEFAULT_FONT_GROUP;

    private final Texture primaryTex;
    private final Texture monoTex;
    private final Texture iconsTex;

    private Atlases(Texture primaryTex, Texture monoTex, Texture iconsTex) {
        this.primaryTex = primaryTex;
        this.monoTex = monoTex;
        this.iconsTex = iconsTex;
    }

    /**
     * Load the three atlas textures + metadata from the classpath and register
     * each as a {@link FontGroup}. Returns a handle that owns the textures.
     */
    public static Atlases loadAndRegister() {
        Texture primaryTex = Texture.fromPngResource("/dasum/atlas/primary.png");
        Texture monoTex = null;
        Texture iconsTex = null;
        try {
            monoTex = Texture.fromPngResource("/dasum/atlas/mono.png");
            iconsTex = Texture.fromPngResource("/dasum/atlas/icons.png");
        } catch (RuntimeException e) {
            // Don't leak already-created textures if a later load fails.
            if (monoTex != null) monoTex.close();
            primaryTex.close();
            throw e;
        }

        FontGroups.register(FontGroup.of(PRIMARY, AtlasData.loadFromResource("/dasum/atlas/primary.json"), primaryTex));
        FontGroups.register(FontGroup.of(MONO, AtlasData.loadFromResource("/dasum/atlas/mono.json"), monoTex));
        FontGroups.register(FontGroup.of(ICONS, AtlasData.loadFromResource("/dasum/atlas/icons.json"), iconsTex));

        return new Atlases(primaryTex, monoTex, iconsTex);
    }

    @Override
    public void close() {
        iconsTex.close();
        monoTex.close();
        primaryTex.close();
    }
}
